controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
login:
    path: /login
    methods: ['POST']
refresh:
    path: /refresh
    methods: ['POST']
self:
    path: /self
    methods: ['GET']
